# Docker Compose file for a single-node Kafka system using KRaft mode.
# Each service (Kafka broker, producers, consumers) runs in its own container.

services:
  kafka:
    image: apache/kafka:latest
    ports:
      - "9092:9092" # Expose Kafka broker for producers and consumers.
    environment:
      # Kafka running in KRaft mode
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093" # Running 1 controller node
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "${BROKER_ADVERTISED_LISTENER}" # All services are on the same Docker network
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_METADATA_LOG_DIR: "/var/lib/kafka/data"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - kafka_storage:/var/lib/kafka/data
    networks:
      - kafka_network

  # Temperature Producer Container
  producer_temp:
    build:
      context: .
    depends_on:
      - kafka
    env_file:
      - .env
    environment:
      KAFKA_BROKER: "${KAFKA_BROKER}"
      PRODUCER_TOPIC: "${TEMP_PRODUCER_TOPIC}"
      PRODUCER_INTERVAL: "${TEMP_PRODUCER_INTERVAL}"
    command: ["./build/temp_producer"]
    networks:
      - kafka_network

  # Virbration Producer Container
  producer_vibration:
    build:
      context: .
    depends_on:
      - kafka
    env_file:
      - .env
    environment:
      KAFKA_BROKER: "${KAFKA_BROKER}"
      PRODUCER_TOPIC: "${VIB_PRODUCER_TOPIC}"
      PRODUCER_INTERVAL: "${VIB_PRODUCER_INTERVAL}"
    command: ["./build/vib_producer"]
    networks:
      - kafka_network

  # Temperature Consumer Container
  consumer_temp:
    build:
      context: .
    depends_on:
      - kafka
      - producer_temp
    env_file:
      - .env
    environment:
      KAFKA_BROKER: "${KAFKA_BROKER}"
      CONSUMER_TOPIC: "${TEMP_CONSUMER_TOPIC}"
      CONSUMER_GROUP: "${TEMP_CONSUMER_GROUP}"
    command: ["./build/temp_consumer"]
    networks:
      - kafka_network

  # Vibration Consumer Container
  consumer_vibration:
    build:
      context: .
    depends_on:
      - kafka
      - producer_vibration
    env_file:
      - .env
    environment:
      KAFKA_BROKER: "${KAFKA_BROKER}"
      CONSUMER_TOPIC: "${VIB_CONSUMER_TOPIC}"
      CONSUMER_GROUP: "${VIB_CONSUMER_GROUP}"
    command: ["./build/vib_consumer"]
    networks:
      - kafka_network

volumes:
  kafka_storage:

networks:
  kafka_network:
